### PR TITLE
generate css with pygments 2.2.0, add makefile, update readme

### PR DESCRIPTION
**Pull request by cs01**

### CODE REVIEW

**Comment by jhabdas** [comment]
@cs01 could you split this into two commits, one which adds the `Makefile` and another which rebuilds the CSS? Having that separation will make this pull much easier to grok and review.

Also, I noticed the CSS generated is missing the wrapper class, which may be changing (but as part of https://github.com/richleland/pygments-css/pull/6)

**Comment by jhabdas** [comment]
Removal of the `.codehilite` class makes it difficult to see some class names [have been removed](https://github.com/richleland/pygments-css/pull/14/files#diff-2a8baf47e8d73c6d6ae400a53696a101L61). That said, it calls to attention code generated with later versions of Pygments may not play as nice with the @richleland classics.

**Comment by cs01** [comment]
Thanks I'll add the class back in.  I doubt the pr will ever be merged though since #6 has been open for two years now, but it's worth a shot.

**Comment by jhabdas** [comment]
Hey, either way it'll help :) Seeing your diffs helped me make this already: https://github.com/comfusion/atom-one-pygments

**Comment by cs01** [comment]
commit 146834e addresses https://github.com/richleland/pygments-css/pull/6

**Comment by jhabdas** [comment]
@richleland would you do the honors? Many many websites are turning to JS for highlighting as a result of #6

**Comment by cs01** [comment]
They can also just use my fork :) https://github.com/cs01/pygments-css. I'm an active github user and respond quickly to updates. 

But I agree with @jhabdas, @richleland, this repo is widely used but out of date. If you no longer want to maintain it, pass the torch on to someone who will.

**Comment by jhabdas** [comment]
To add a little more color, Rich, the beautiful static Web is about to come back in a big way thanks to Hugo. Check out the Smashing Magazine article from Netifly for more background.

**Comment by richleland** [comment]
Thanks for submitting @cs01. To be honest I wasn't aware it was used widely - I haven't done anything with pygments in years or worked on anything using it. Issues (4 in 8 years) and PRs (the last coming in Oct 2015) have been rare for the repo, so I don't keep as close an eye on it, but happy to keep closer watch moving forward.

Thanks again for the PR and nudging!

**Pull request merged**
